In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# prediction of chance of admission(COA)
admissiondataset=pd.read_csv('Admission_Predict.csv')
#admissiondataset.columns
#admissiondataset.info()
admissiondataset.head()

   Serial No.  GRE  TOEFL  UR  SOP  LOR  CGPA  Research   COA
0           1  337    118   4  4.5  4.5  9.65         1  0.92
1           2  324    107   4  4.0  4.5  8.87         1  0.76
2           3  316    104   3  3.0  3.5  8.00         1  0.72
3           4  322    110   3  3.5  2.5  8.67         1  0.80
4           5  314    103   2  2.0  3.0  8.21         0  0.65

In [15]:
# threshold value for target variable and change value of COA with category value ie greater than 75 1 less than 75 0
admissiondataset['COA'] = np.where(admissiondataset['COA']>.75,1,0)
#admissiondataset['COA'].value_counts()

COA
0    228
1    172
Name: count, dtype: int64

In [17]:
Y = admissiondataset['COA']
X = admissiondataset.drop(['Serial No.','COA'],axis=1)

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_Train,X_Test,Y_Train,Y_Test=train_test_split(X,Y,test_size=.2,random_state=1)
logmodel = LogisticRegression(random_state=1)
logmodel.fit(X_Train,Y_Train)
Y_Predict = logmodel.predict(X_Test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_Test,Y_Predict)
#Save your trained model
#import joblib
#joblib.dump(logmodel, 'model.pkl')

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9125

In [44]:
#create a data frme to show X_test,Y_test and Y predict 
Analysis=X_Test.copy()
Analysis['Y_Test']=Y_Test
Analysis['Y_Predict']=Y_Predict
Analysis

     GRE  TOEFL  UR  SOP  LOR  CGPA  Research  Y_Test  Y_Predict
398  312    103   3  3.5  4.0  8.78         0       0          0
125  300    100   3  2.0  3.0  8.66         1       0          0
328  324    112   4  4.0  3.5  8.77         1       1          1
339  324    107   5  3.5  4.0  8.66         1       1          1
172  322    110   4  4.0  5.0  9.13         1       1          1
..   ...    ...  ..  ...  ...   ...       ...     ...        ...
347  299     94   1  1.0  1.0  7.34         0       0          0
41   316    105   2  2.5  2.5  8.20         1       0          0
180  300    104   3  3.5  3.0  8.16         0       0          0
132  309    105   5  3.5  3.5  8.56         0       0          0
224  305    105   2  3.0  2.0  8.23         0       0          0

[80 rows x 9 columns]

In [71]:
# Identify wrong predictions
wrong_predictions = Analysis[Analysis['Y_Test'] != Analysis['Y_Predict']]

print(wrong_predictions)

     GRE  TOEFL  UR  SOP  LOR  CGPA  Research  Y_Test  Y_Predict
242  324    115   3  3.5  3.0  8.76         1       0          1
139  318    109   1  3.5  3.5  9.12         0       1          0
389  320    108   3  3.5  4.0  8.44         1       1          0
65   325    112   4  3.5  3.5  8.92         0       0          1
18   318    110   3  4.0  3.0  8.80         0       0          1
296  310    107   3  3.5  3.5  8.67         0       1          0
310  320    104   3  3.0  3.5  8.74         1       1          0